sonar.organization=gszigethy
sonar.projectKey=gszigethy_vwgroup-connect-ha

sonar.sources=custom_components,scripts
sonar.tests=tests

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=custom_components/**/translations/**,**/*.png
sonar.test.exclusions=tests/fixtures/**
sonar.cpd.exclusions=tests/**
